/* PSC18SR host firmware -- drives the core as a non-boot side block.
 *
 * Built for targets/colorlight_i9/psc18sr.py, where PSC18SR hangs off the SoC
 * as an ordinary peripheral: this CPU boots normally, owns the console, and is
 * in no way downstream of the core. That is what makes it safe to run an
 * unproven ISA here -- a wedged program is a `control.abort` away, not a power
 * cycle, and test 4 below proves exactly that escape works.
 *
 *   cd software/psc18sr_host && make BUILD_DIR=../../build/colorlight_i5
 *   litex_term /dev/icelink-uart --speed 115200 \
 *              --kernel software/psc18sr_host/psc18sr_host.bin
 *
 * The programs come from the .s files in software/psc18sr_test via psc18sr_asm.py
 * (see programs.h, regenerated by the Makefile). Each program's own comments
 * state the result it promises; this file checks that promise and nothing
 * more, so the .s files stay the specification.
 *
 * Register/field layout is written out as bit masks rather than LiteX field
 * accessors on purpose: whole-CSR read/write is generated by every LiteX
 * version this tree has been built against, per-field accessors are not.
 */
#include <stdint.h>

#include <irq.h>
#include <libbase/uart.h>
#include <system.h>
#include <generated/csr.h>
#include <generated/soc.h>

#include "programs.h"

/* ---- tiny UART logging ------------------------------------------------- */
static void log_char(char c) { if (c == '\n') uart_write('\r'); uart_write(c); }
static void log_puts(const char *s) { while (*s) log_char(*s++); }
static void log_nl(void) { log_char('\n'); uart_sync(); }
static void log_hex4(uint8_t v) { v &= 0x0f; log_char(v < 10 ? '0' + v : 'a' + v - 10); }
static void log_hex16(uint16_t v)
{
	log_hex4(v >> 12); log_hex4(v >> 8); log_hex4(v >> 4); log_hex4(v);
}
static void log_uint(uint32_t v)
{
	char buf[10];
	unsigned int i = 0;
	if (v == 0) { log_char('0'); return; }
	while (v && i < sizeof(buf)) { buf[i++] = '0' + v % 10; v /= 10; }
	while (i) log_char(buf[--i]);
}

#ifdef CSR_PSC18SR_BASE

/* ---- CSR bit layout (gateware/psc18sr.py) ------------------------------ */
#define CTL_RUN		(1u << 0)	/* pulse */
#define CTL_ABORT	(1u << 1)	/* pulse */

#define ST_RUNNING	(1u << 0)
#define ST_HALTED	(1u << 1)
#define ST_ABORTED	(1u << 2)
#define ST_WDT		(1u << 3)

#define IMEM_WE		(1u << 0)

/* Both come from the gateware as generated constants (see add_psc18sr), so a
 * build with --psc18sr-prescale or --psc18sr-ro-words overridden still tests
 * itself rather than testing the defaults. */
#define PRESCALE	PSC18SR_DELAY_PRESCALE
#define RO_WORDS	PSC18SR_RO_WORDS

/* Generous: the longest program here is seq.s, whose two DELAYs are ~9 ms at
 * the default prescale. Anything past this is a hang, not slowness. */
#define POLL_LIMIT	20000000u

static unsigned int failures;

/* ---- driver ------------------------------------------------------------ */
static inline uint32_t psc_status(void)  { return psc18sr_status_read(); }
static inline int psc_halted(void)  { return (psc_status() & ST_HALTED)  != 0; }
static inline int psc_running(void) { return (psc_status() & ST_RUNNING) != 0; }
static inline void psc_abort(void)  { psc18sr_control_write(CTL_ABORT); }

/* Load at the program's own origin. Writes below ro_words are ignored by the
 * core by design, so a program assembled with a too-low .org silently does not
 * arrive -- say so rather than reporting a mystery failure. */
static int psc_load(const uint32_t *prog, unsigned int n, unsigned int org)
{
	if (org < RO_WORDS) {
		log_puts("  *** program origin ");
		log_uint(org);
		log_puts(" is below the read-only region; it will not load");
		log_nl();
		return -1;
	}
	for (unsigned int i = 0; i < n; i++) {
		psc18sr_imem_addr_write(org + i);
		psc18sr_imem_data_write(prog[i]);
		psc18sr_imem_ctl_write(IMEM_WE);
	}
	return 0;
}

static void psc_start(unsigned int org)
{
	psc18sr_start_pc_write(org);
	psc18sr_control_write(CTL_RUN);
}

/* Run to HLT. Returns -1 on timeout, having aborted the core so the next test
 * starts from a known state. */
static int psc_wait_halt(void)
{
	for (uint32_t i = 0; i < POLL_LIMIT; i++)
		if (psc_halted())
			return 0;
	log_puts("  *** timeout: core still running at pc=");
	log_uint(psc18sr_dbg_pc_read());
	log_puts(", aborting");
	log_nl();
	psc_abort();
	return -1;
}

static uint32_t psc_exec(const uint32_t *prog, unsigned int n, unsigned int org)
{
	psc_abort();                    /* known state, whatever the last test left */
	if (psc_load(prog, n, org) != 0)
		return 0xffffffffu;
	psc_start(org);
	if (psc_wait_halt() != 0)
		return 0xffffffffu;
	return psc18sr_result_read();
}

/* ---- a free-running cycle counter, for the DELAY check ----------------- */
/* timer0 exists in every SoCCore. Used directly rather than through
 * libbase/time.h's busy_wait so nothing else in this firmware fights over it. */
static void cyc_start(void)
{
	timer0_en_write(0);
	timer0_load_write(0xffffffffu);
	timer0_reload_write(0);
	timer0_en_write(1);
}

static uint32_t cyc_elapsed(void)
{
	timer0_update_value_write(1);
	return 0xffffffffu - timer0_value_read();
}

/* ---- reporting --------------------------------------------------------- */
static void report(const char *name, uint32_t got, uint32_t want)
{
	log_puts("  "); log_puts(name);
	log_puts(": got 0x");  log_hex16((uint16_t)got);
	log_puts(" want 0x");  log_hex16((uint16_t)want);
	if (got == want) {
		log_puts("   PASS");
	} else {
		log_puts("   *** FAIL ***");
		failures++;
	}
	log_nl();
}

/* ---- tests ------------------------------------------------------------- */

/* 1/2: pure compute. sum.s is v1's hello-world; shift.s is the 2026-09-12
 * addition, and reports the index of its own failing check as its result. */
static void test_sum(void)
{
	report("sum.s   (LI/ALU/ADDI/BNE)",
	       psc_exec(psc18sr_sum, PSC18SR_SUM_WORDS, PSC18SR_SUM_ORG), 55);
}

static void test_shift(void)
{
	report("shift.s (SLL/SRL/SRA)",
	       psc_exec(psc18sr_shift, PSC18SR_SHIFT_WORDS, PSC18SR_SHIFT_ORG), 0x5a);
}

/* Wait for gpio_out port0 bit0 to reach `level`. Returns 0, or -1 on timeout.
 *
 * Every port watch here is written as "wait for the level it is heading to",
 * never "wait for it to leave the level it is on": io_out survives an abort
 * and only a core reset clears it, so the starting level is whatever the last
 * test left behind, and a poll for "goes low" would pass instantly on a port
 * that was already low. */
static int wait_out0(unsigned int level)
{
	for (uint32_t i = 0; i < POLL_LIMIT; i++)
		if ((psc18sr_gpio_out_read() & 1u) == level)
			return 0;
	return -1;
}

/* 3: the sequencing half -- the instructions that justify the core existing.
 * seq.s drives gpio_out port0 bit0 high, low for 415 DELAY ticks, then high
 * again, and parks in WAIT until gpio_in port0 bit0 goes high. Watching that
 * from here checks BITOP drives a real port, DELAY takes the time it claims,
 * and WAIT actually blocks and actually releases. */
static void test_seq(void)
{
	uint32_t low_cycles, expect;

	psc_abort();
	psc18sr_gpio_in_write(0);
	if (psc_load(psc18sr_seq, PSC18SR_SEQ_WORDS, PSC18SR_SEQ_ORG) != 0)
		return;
	psc_start(PSC18SR_SEQ_ORG);

	if (wait_out0(1) != 0 || wait_out0(0) != 0) {
		log_puts("  *** seq.s: no high-then-low on gpio_out bit0 (BITOP?)");
		log_nl();
		failures++; psc_abort(); return;
	}
	cyc_start();
	if (wait_out0(1) != 0) {
		log_puts("  *** seq.s: gpio_out bit0 never came back high"); log_nl();
		failures++; psc_abort(); return;
	}
	low_cycles = cyc_elapsed();

	/* It should now be parked in WAIT: having driven the port and spent the
	 * delay, still running, and never halting until we say so. */
	if (psc_halted()) {
		log_puts("  *** seq.s: halted before WAIT was satisfied"); log_nl();
		failures++;
	}

	/* CONFIG_CLOCK_FREQUENCY is the frequency that was ASKED FOR, not the one
	 * the PLL produces: on the i9, 48 MHz requested comes out as
	 * 25 x 21 / 11 = 47.727 MHz, so this microsecond figure reads ~0.6% low.
	 * The cycle count beside it is exact, and it is the one the check below
	 * uses -- comparing cycles to cycles takes the clock out of the question
	 * entirely. */
	log_puts("  seq.s   reset-low pulse: ");
	log_uint(low_cycles / (CONFIG_CLOCK_FREQUENCY / 1000000u));
	log_puts(" us nominal (");
	log_uint(low_cycles);
	log_puts(" cycles, exact)"); log_nl();

	/* seq.s spends its 415 ticks as a LOOP of `DELAY 1`, because DELAY takes
	 * an immediate and the count is in a register -- so each tick costs
	 * PRESCALE cycles for the stall plus 12 for the instructions around it:
	 * DELAY's own fetch/decode/exec (3) and the BEQ/ADDI/JMP of the loop
	 * (9). That is 1.2% of a tick at the default prescale and 300% of one at
	 * prescale 4, which is worth knowing before anyone writes a tight
	 * variable-length wait. Simulation says 429954 cycles against the 429940
	 * this predicts, so 2% is a real check on DELAY, not a rubber stamp --
	 * the slack is for the CPU's polling granularity at each end. */
	expect = 415u * (PRESCALE + 12u);
	report("seq.s   DELAY within 2% of expected",
	       (low_cycles > expect - expect / 50u && low_cycles < expect + expect / 50u),
	       1);

	psc18sr_gpio_in_write(1);               /* release the WAIT */
	if (psc_wait_halt() != 0) {
		log_puts("  *** seq.s: WAIT did not release on gpio_in bit0"); log_nl();
		failures++;
		return;
	}
	report("seq.s   (BITOP/DELAY/WAIT/JAL)", psc18sr_result_read(), 0xa5);
}

/* 4: the escape hatch. An unbounded WAIT is by design, so the thing that has
 * to work is abort -- on a stage-0 build the watchdog covers this, and here
 * the CPU does. Deliberately reproduces sketch finding F5. */
static void test_abort(void)
{
	psc_abort();
	psc18sr_gpio_in_write(0);               /* nobody will ever say ready */
	if (psc_load(psc18sr_seq, PSC18SR_SEQ_WORDS, PSC18SR_SEQ_ORG) != 0)
		return;
	psc_start(PSC18SR_SEQ_ORG);

	/* Run it up to the stall rather than guessing at a delay: the second
	 * rising edge is the instruction immediately before WAIT. */
	if (wait_out0(1) != 0 || wait_out0(0) != 0 || wait_out0(1) != 0) {
		log_puts("  *** abort: seq.s did not reach its WAIT"); log_nl();
		failures++; psc_abort(); return;
	}
	if (psc_halted()) {
		log_puts("  *** abort: core halted on its own; nothing to escape"); log_nl();
		failures++;
		return;
	}
	psc_abort();
	report("abort   stops a wedged WAIT", psc_running() ? 1 : 0, 0);
	report("abort   is distinguishable from HLT",
	       (psc_status() & ST_ABORTED) ? 1 : 0, 1);
}

/* 5: BUS -- the instruction v1 has no equivalent of. bus.s writes 42 into this
 * core's OWN gpio_in CSR through the Wishbone window and reads it back with
 * IN, so a pass exercises the window base, the address arithmetic, the
 * read-modify-write half-word store, and the CSR landing where IN can see it,
 * with no other peripheral having to cooperate.
 *
 * The CSR offset is a build-time fact, so the program's constant pool is
 * patched here rather than hard-coded in the .s -- gpio_in does not land at
 * the same offset on two different SoCs. gpio_in is 64 bits = two CSR words
 * and LiteX orders them big-endian, so bits [31:0] are the SECOND word, and
 * port 0 is its low half. */
static void test_bus(void)
{
	uint32_t prog[PSC18SR_BUS_WORDS];
	uint32_t off = (CSR_PSC18SR_GPIO_IN_ADDR - CSR_BASE) + 4;
	uint32_t got;

	for (unsigned int i = 0; i < PSC18SR_BUS_WORDS; i++)
		prog[i] = psc18sr_bus[i];
	prog[PSC18SR_BUS_L_POOL - PSC18SR_BUS_ORG] = off;

	psc18sr_gpio_in_write(0);
	got = psc_exec(prog, PSC18SR_BUS_WORDS, PSC18SR_BUS_ORG);

	log_puts("  bus.s   gpio_in CSR at window offset 0x");
	log_hex16((uint16_t)off); log_nl();
	report("bus.s   BUS write -> IN readback", got, 42);
	/* And from this side of the bus, which the core never touched directly. */
	report("bus.s   CPU sees the same CSR",
	       (uint32_t)(psc18sr_gpio_in_read() & 0xffffu), 42);
	psc18sr_gpio_in_write(0);
}

static void run_tests(void)
{
	failures = 0;
	log_puts("PSC18SR side-block self-test:"); log_nl();

	test_sum();
	test_shift();
	test_seq();
	test_abort();
	test_bus();

	if (failures) {
		log_puts("*** ");
		log_uint(failures);
		log_puts(" FAILED ***");
	} else {
		log_puts("all passed");
	}
	log_nl();
}
#endif /* CSR_PSC18SR_BASE */

int main(void)
{
	uart_init();
#ifdef CONFIG_CPU_HAS_INTERRUPT
	irq_setie(1);
#endif
	log_nl();
	log_puts("psc18sr_host firmware up. sys clk = ");
	log_uint(CONFIG_CLOCK_FREQUENCY); log_puts(" Hz"); log_nl();

#ifdef CSR_PSC18SR_BASE
	run_tests();
	log_puts("done. press any key to re-run."); log_nl();
	for (;;) {
		(void)uart_read();
		run_tests();
		log_puts("done. press any key to re-run."); log_nl();
	}
#else
	log_puts("ERROR: this SoC has no PSC18SR (CSR_PSC18SR_BASE undefined)."); log_nl();
	for (;;)
		;
#endif
	return 0;
}
