#!/usr/bin/env python3
"""Generate the embedded-asset C header for the on-FPGA MNIST touch demo.

The standalone touch demo (software/mnist_lcd_demo) has no host attached, so
the weight blob, biases, and loader CSR values are baked into the firmware
image instead of streamed over UART. This script emits a single header:

    software/mnist_lcd_demo/snn_assets.h

containing:
  - snn_weights_blob[]  : the exact tile-major blob snn_weight_loader.v expects,
                          byte-identical to tools/pack_snn_mnist_weights.py output
                          (reused here so there is one source of truth).
  - snn_biases[]        : 74 Q4.12 biases (HIDDEN then OUT_SIZE).
  - SNN_* defines       : beats_per_cycle, num_cycles, input_scale (Q12), frac_bits.

The blob is placed in .rodata (SDRAM) and the firmware points the loader's
weight_base CSR straight at its address -- no memcpy, no fixed 1 MiB offset.
A 4-byte alignment attribute satisfies the loader's word-addressed Wishbone
master (gateware/snn_mlp.py drops the low 2 address bits).

Usage:
    .venv/bin/python tools/gen_mnist_demo_assets.py --n-mac 2
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from sim.snn_mlp import load_checkpoint
from tools.pack_snn_mnist_weights import pack_one_step, pack_biases


def emit_byte_array(name: str, data: bytes, align: int = 4) -> str:
    lines = [
        f"static const unsigned char {name}[{len(data)}] "
        f"__attribute__((aligned({align}))) = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    return "\n".join(lines)


def emit_i16_array(name: str, values: list[int]) -> str:
    lines = [f"static const short {name}[{len(values)}] = {{"]
    for i in range(0, len(values), 12):
        chunk = values[i:i + 12]
        lines.append("    " + " ".join(f"{v}," for v in chunk))
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", type=Path, default=REPO / "build" / "snn_mnist.pt")
    parser.add_argument("--n-mac", type=int, default=2,
                        help="Must match SNNMLP's N_MAC in icepi_zero_mnist_lcd.py (default 2).")
    parser.add_argument("--out", type=Path,
                        default=REPO / "software" / "mnist_lcd_demo" / "snn_assets.h")
    args = parser.parse_args()

    model = load_checkpoint(args.checkpoint)
    cfg = model.config
    blob, beats = pack_one_step(model, args.n_mac)
    biases = pack_biases(model)

    frac_bits = cfg.frac_bits
    # pixel_q = round(gray01 * input_scale * 2^frac_bits). Bake the scale factor
    # (input_scale << frac_bits) so the firmware does pure integer math.
    input_scale_q = int(round(cfg.input_scale * (1 << frac_bits)))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    header = f"""\
/* Auto-generated by tools/gen_mnist_demo_assets.py -- DO NOT EDIT BY HAND.
 *
 * checkpoint : {args.checkpoint.name}
 * shape      : {cfg.in_size}->{cfg.hidden}->{cfg.out_size}  T={cfg.timesteps}
 * n_mac      : {args.n_mac}
 * blob       : {len(blob)} bytes ({beats} beats * 4)
 */
#pragma once

#define SNN_IN_SIZE          {cfg.in_size}
#define SNN_HIDDEN           {cfg.hidden}
#define SNN_OUT_SIZE         {cfg.out_size}
#define SNN_BIAS_COUNT       {len(biases)}
#define SNN_BEATS_PER_CYCLE  {beats}u
#define SNN_NUM_CYCLES       {cfg.timesteps}u
#define SNN_FRAC_BITS        {frac_bits}
/* pixel_q = (gray01 * SNN_INPUT_SCALE_Q) >> 0, where gray01 is already scaled
 * to [0, 2^FRAC_BITS]. With input_scale={cfg.input_scale} this is the identity. */
#define SNN_INPUT_SCALE_Q    {input_scale_q}

{emit_byte_array("snn_weights_blob", blob)}

{emit_i16_array("snn_biases", biases)}
"""
    args.out.write_text(header)
    print(f"wrote {args.out}  ({len(blob)} byte blob, {len(biases)} biases, "
          f"beats={beats}, T={cfg.timesteps}, input_scale_q={input_scale_q})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
